==========================================
SLURM_JOB_ID = 8153186
SLURM_SUBMIT_DIR = /project/kh_mercury_1
SLURM_JOB_NODELIST = mcn31
==========================================
Job ID: 8153186
Job User: pspahwa
Num Cores: 16
Traceback (most recent call last):
  File "DirectSearch/updatedDS/possibleNamesDS.py", line 43, in <module>
    main(sys.argv[1], sys.argv[2])
  File "DirectSearch/updatedDS/possibleNamesDS.py", line 39, in main
    news_df = news_df.compute(scheduler = "processes")
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/base.py", line 283, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/base.py", line 565, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/multiprocessing.py", line 230, in get
    **kwargs
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/local.py", line 487, in get_async
    raise_exception(exc, tb)
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/multiprocessing.py", line 120, in reraise
    raise exc
dask.multiprocessing.ValueError: malformed node or string: <_ast.Name object at 0x7f4f9df4fb70>

Traceback
---------
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/optimization.py", line 963, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/core.py", line 151, in get
    result = _execute_task(task, cache)
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/core.py", line 121, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/optimization.py", line 963, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/core.py", line 151, in get
    result = _execute_task(task, cache)
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/utils.py", line 35, in apply
    return func(*args, **kwargs)
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/dataframe/core.py", line 5487, in apply_and_enforce
    df = func(*args, **kwargs)
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/utils.py", line 901, in __call__
    return getattr(obj, self.method)(*args, **kwargs)
  File "/apps/python/3.6/3.6.12/lib/python3.6/site-packages/pandas/core/frame.py", line 7552, in apply
    return op.get_result()
  File "/apps/python/3.6/3.6.12/lib/python3.6/site-packages/pandas/core/apply.py", line 185, in get_result
    return self.apply_standard()
  File "/apps/python/3.6/3.6.12/lib/python3.6/site-packages/pandas/core/apply.py", line 276, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/apps/python/3.6/3.6.12/lib/python3.6/site-packages/pandas/core/apply.py", line 305, in apply_series_generator
    results[i] = self.f(v)
  File "DirectSearch/updatedDS/possibleNamesDS.py", line 34, in <lambda>
    news_df["Firms Mentioned"] = news_df.apply(lambda x: find_firms_associated_with_news(x, all_company_lists), meta = "str", axis = 1)
  File "DirectSearch/updatedDS/possibleNamesDS.py", line 18, in find_firms_associated_with_news
    for company_list in all_company_lists:
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/dataframe/core.py", line 3060, in __iter__
    s = self.get_partition(i).compute()
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/base.py", line 283, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/base.py", line 565, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/threaded.py", line 84, in get
    **kwargs
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/local.py", line 487, in get_async
    raise_exception(exc, tb)
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/local.py", line 317, in reraise
    raise exc
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/optimization.py", line 963, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/core.py", line 151, in get
    result = _execute_task(task, cache)
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/core.py", line 121, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/core.py", line 121, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/optimization.py", line 963, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/core.py", line 151, in get
    result = _execute_task(task, cache)
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/utils.py", line 35, in apply
    return func(*args, **kwargs)
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/dataframe/core.py", line 5487, in apply_and_enforce
    df = func(*args, **kwargs)
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/utils.py", line 901, in __call__
    return getattr(obj, self.method)(*args, **kwargs)
  File "/apps/python/3.6/3.6.12/lib/python3.6/site-packages/pandas/core/series.py", line 4213, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2403, in pandas._libs.lib.map_infer
  File "/apps/python/3.6/3.6.12/lib/python3.6/ast.py", line 85, in literal_eval
    return _convert(node_or_string)
  File "/apps/python/3.6/3.6.12/lib/python3.6/ast.py", line 61, in _convert
    return list(map(_convert, node.elts))
  File "/apps/python/3.6/3.6.12/lib/python3.6/ast.py", line 84, in _convert
    raise ValueError('malformed node or string: ' + repr(node))

srun: error: mcn31: task 0: Exited with exit code 1
